version: '3.7'
services:      
    blockchain_server:
        build:
            context: .
        container_name: blockchain
        environment:
            - TZ=Asia/Taipei
        restart: always
        ports:
            - 1203:1203
        command: >
            /bin/bash -c "
            sleep 1;
            ./build/main server test;"
        networks:
            vpcbr:
                ipv4_address: 172.28.0.3
    blockchain_node1:
        build:
            context: .
        container_name: node1
        environment:
            - TZ=Asia/Taipei
        restart: always
        command: >
            /bin/bash -c "
            sleep 2;
            ./build/main node test;"
        networks:
            vpcbr:
                ipv4_address: 172.28.0.4

    # blockchain_node2:
    #     build:
    #         context: .
    #     node_2: blockchain
    #     environment:
    #         - TZ=Asia/Taipei
    #     restart: always
    #     command: >
    #         /bin/bash -c "
    #         sleep 2;
    #         ./build/main node;"
    #     networks:
    #         vpcbr:
    #             ipv4_address: 172.28.0.5

    # blockchain_node3:
    #     build:
    #         context: .
    #     node_3: blockchain
    #     environment:
    #         - TZ=Asia/Taipei
    #     restart: always
    #     command: >
    #         /bin/bash -c "
    #         sleep 2;
    #         ./build/main node;"
    #     networks:
    #         vpcbr:
    #             ipv4_address: 172.28.0.6
            

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16